#include<stdio.h>
#include<stdlib.h>
#include<ctype.h>
#include<conio.h>
#include<time.h>
int main(void)
{
    //for different questions for every run
    srand(time(NULL));
    char* playername[20];
    char c;
    char* ans1[] = {'C','C','C','B','B','B','D','A','A','B'};
    char* ans2[] = {'A','C','B','D','B','B','C','D','C','D','C','B','C','A','C','D','A','C','B','D','D','D','D','B','D','C','D','D','B','A'};
    int i, j, score = 0;
    //to store question number for different question in the same run
    int num[5], num2[10];
    int count = 0;
    mainmenu:
    system("cls");
    printf("\t\t\t         WELCOME");
    printf("\n\t\t\t           TO");
    printf("\n\t\t\t THE BEST QUIZ GAME EVER");
    printf("\n\t\t\t--------------------------");
    printf("\n\t\t\t--------------------------");
    printf("\n\t\t\t>PRESS S - TO START THE GAME");
    printf("\n\t\t\t>PRESS H - FOR HELP");
    printf("\n\t\t\t>PRESS R - TO RESET THE SCORE");
    printf("\n\t\t\t>PRESS V - TO VIEW THE HIGHEST SCORE");
    printf("\n\t\t\t>PRESS Q - TO QUIT");
    printf("\n");
    //to start the game
    char choice = toupper(getch());
    if(choice == 'S')
    {
        system("cls");
        printf("\n\n\n\n\n\n\n\n\t\t\tREGISTER YOUR NAME: ");
        gets(playername);
        system("cls");
        printf("\n ------------------  Welcome %s to C Program Quiz Game --------------------------",playername);
        printf("\n\n Here are some tips you might wanna know before playing:");
        printf("\n -------------------------------------------------------------------------");
        printf("\n >> There are 2 rounds in this Quiz Game,QUALIFICATION ROUND & FINAL ROUND");
        printf("\n >> In QUALIFICATION round you will be asked a total of 5 questions to test your");
        printf("\n    general knowledge. You are eligible to play the game if you give atleast 3");
        printf("\n    right answers, otherwise you can't proceed further to the FINAL Round.");
        printf("\n >> Your game starts with FINAL ROUND. In this round you will be asked a");
        printf("\n    total of 10 questions. Each right answer will be awarded $100,000!");
        printf("\n    By this way you can win upto ONE MILLION cash prize!!!!!..........");
        printf("\n >> You will be given 4 options and you have to press A, B ,C or D for the");
        printf("\n    right option.");
        printf("\n >> You will be asked questions continuously, till right answers are given");
        printf("\n >> No negative marking for wrong answers!");
        printf("\n\n\t!!!!!!!!!!!!! ALL THE BEST !!!!!!!!!!!!!");
        printf("\npress Y to start the game");
        printf("\npress any other key to go to main menu");
        if(toupper(getch()) == 'Y')
        {
            system("cls");
            printf("\n\n\n\n\n\n\n\n\t\t\t     LET'S START");
            printf("\n\t\t\t        WITH");
            printf("\n\t\t\t QUALIFICATION ROUND");
            printf("\n\n\n\t\t\t press any key to continue:");
            if(getch())
                system("cls");
            //open the file for qualification round
            FILE* ptr = fopen("quiz1.txt", "r");
            //for temporary storage of question
            char * buffer[1024];
            //to display five questions for qualification round
            for(j = 0; j< 5; j++)
            {
                //generate a random number between 1 to 10
                l : num[j] = (rand() % 10) + 1;
                //to check previous question doesn't display in the same run
                for(int a = 0; a < j; a++)
                {
                    if(num[j] == num[a])
                        goto l;
                }
                //to display the question
                for(i = 1; i <=10; i++)
                {
                    //temporary storage of question in buffer
                    fgets(buffer, 1024, ptr);
                    //to check if the end of file is reached
                    if(i == 10)
                     {
                        //if so, place the file pointer at the beginning
                        fseek(ptr, 0, SEEK_SET);
                     }
                    //to print the question number generated by rand()
                    if(i == num[j])
                    {
                        //prints the question
                        printf("%d\t",num[j]);
                        puts(buffer);
                        printf("\n\n enter your option: ");
                        scanf(" %c", &c);
                        if(toupper(c) == ans1[i-1])
                         {
                             printf("\ncorrect!!!!");
                             count++;
                             if(getch())
                                system("cls");
                         }
                         else
                         {
                             printf("\nwrong!!!!");
                             if(getch())
                                system("cls");
                         }
                    }
                }
            }
            if(count >= 3)
            {
                    printf("\n\n\n\n\n\n\n\n\n\n\nCONGATULATIONS");
                    printf("\n                         YOU");
                    printf("\n                    HAVE QUALIFIED");
                    printf("\n                THE QUALIFICATION ROUND");
            }

            else
            {
                printf("\n\n\n\n\n\n\n\n\n\\n\n\n SORRY");
                printf("\n YOU DIDN'T QUALIFY THE QUALIFICATION ROUND");
                printf("\n BETTER LUCK NEXT TIME");
                getch();
                system("cls");
                goto mainmenu;
            }

            getch();
            system("cls");
            printf("\n\n\n\n\n\n\n\n\n\n\nLET'S START THE FINAL ROUND");
            system("cls");
            FILE* ptr2 = fopen("quiz2.txt", "r");
            //for temporary storage of question
            char * buffer2[1024];
            //to display five questions for qualification round
            for(j = 0; j< 10; j++)
            {
                //generate a random number between 1 to 10
                l1 : num2[j] = (rand() % 30) + 1;
                //to check previous question doesn't display in the same run
                for(int a = 0; a < j; a++)
                {
                    if(num2[j] == num2[a])
                        goto l1;
                }
                //to display the question
                for(i = 1; i <=30; i++)
                {
                    //temporary storage of question in buffer
                    fgets(buffer2, 1024, ptr2);
                    //to check if the end of file is reached
                    if(i == 30)
                     {
                        //if so, place the file pointer at the beginning
                        fseek(ptr2, 0, SEEK_SET);
                     }
                    //to print the question number generated by rand()
                    if(i == num2[j])
                    {
                        //prints the question
                        printf("%d\t",num2[j]);
                        puts(buffer2);
                        printf("\n\n enter your option: ");
                        scanf(" %c", &c);
                        if(toupper(c) == ans2[i-1])
                         {
                             printf("\ncorrect!!!!");
                             score += 100000;

                             if(getch())
                                system("cls");
                         }
                         else
                         {
                             printf("\nwrong!!!!");
                             if(getch())
                                system("cls");
                             printf("\n\n\n\n\n\n\n\n\n\n\nOOPS! YOU LOST.");
                             printf("\nYOU WON ONLY $%d",score);
                             printf("\nBETTER LUCK NEXT TIME");
                             goto scores;
                         }
                    }
                }
            }
            if(score == 1000000)
            {
                printf("\n\n\n\n\n\n\n\n\n\n\n\nCONGRATULATIONS!!!!!!");
                printf("\nYOU WON THE GAME.");
                printf("\nAND");
                printf("THE CASH PRIZE OF $1 MILLION.");
                goto scores;
            }
            scores:
            fclose(ptr2);
            FILE* read = fopen("scores.txt","r");
            int s;
            s = fscanf(read, "%d", &s);
            printf("%d", s);
            fclose(read);
            printf("s: ", s);
            if(score >= s)
            {
                FILE* write = fopen("scores.text", "w");
                fprintf(write, "%d", score);
                fclose(write);
            }
            if(getch())
                goto mainmenu;
        }
        else
        {
            //if any other key is pressed in the welcome screen
            goto mainmenu;
        }
    }
    if(choice == 'H')
    {

        system("cls");
        printf("\n ------------------  Welcome %s to C Program Quiz Game --------------------------",playername);
        printf("\n\n Here are some tips you might wanna know before playing:");
        printf("\n -------------------------------------------------------------------------");
        printf("\n >> There are 2 rounds in this Quiz Game,QUALIFICATION ROUND & FINAL ROUND");
        printf("\n >> In QUALIFICATION round you will be asked a total of 5 questions to test your");
        printf("\n    general knowledge. You are eligible to play the game if you give atleast 3");
        printf("\n    right answers, otherwise you can't proceed further to the FINAL Round.");
        printf("\n >> Your game starts with FINAL ROUND. In this round you will be asked a");
        printf("\n    total of 10 questions. Each right answer will be awarded $100,000!");
        printf("\n    By this way you can win upto ONE MILLION cash prize!!!!!..........");
        printf("\n >> You will be given 4 options and you have to press A, B ,C or D for the");
        printf("\n    right option.");
        printf("\n >> You will be asked questions continuously, till right answers are given");
        printf("\n >> No negative marking for wrong answers!");
        printf("\n\n\t!!!!!!!!!!!!! ALL THE BEST !!!!!!!!!!!!!");
        getch();
        goto mainmenu;
    }
    if(choice == 'Q')
    {
        exit(1);
    }
    if(choice == 'R')
    {
        FILE* reset = fopen("scores.txt", "w");
        int s2 = 0;
        fprintf(reset, "%d", &s2);
        system("cls");
        printf("\n\n\n\n\n\n\n\n\n\nscore has been resetted.");
        getch();
        goto mainmenu;
        fclose(reset);
    }
    if(choice == 'V')
    {
        system("cls");
        FILE* view = fopen("scores.txt", "r");
        int s3;
        s3 = fscanf(view, "%d", &s3);
        printf("THE HIGHEST SCORE IS $%d", s3);
        if(getch())
            goto mainmenu;
        fclose(view);

    }
}
